name: Maven Build and Test

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2 # Specify the version, e.g., uses: actions/checkout@v2.5.0

    - name: Set up JDK 11
      uses: actions/setup-java@v2 # Specify the version, e.g., uses: actions/setup-java@v2.5.2
      with:
        distribution: 'adopt'
        java-version: '11'

    - name: Build with Maven
      run: mvn clean install -DskipTests=true

    - name: Run Tests
      run: mvn test
